name: pmayard_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  flutter_svg: ^2.2.0
  get: ^4.7.2
  pinput: ^5.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  logger: ^2.6.1
  mime_type: ^1.0.1
  intl: ^0.20.2
  timeago: ^3.7.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_widget_from_html: ^0.17.0
  permission_handler: ^12.0.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  socket_io_client: ^3.1.2
  connectivity_plus:
  lottie: ^3.3.1
  curved_labeled_navigation_bar: ^2.0.6
  chat_bubbles: ^1.7.0
  intl_phone_number_input: ^0.7.4
  table_calendar: ^3.2.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  record: ^6.1.2
  audioplayers: ^6.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true
    # rive: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf




#  fvm flutter pub get
#  fvm flutter pub run flutter_launcher_icons


    #===========>>>>>>>>>> Flutter Gen Code ==============>>>>>>>>>>>
    # fvm dart pub global activate flutter_gen
    # fvm flutter pub run build_runner build --delete-conflicting-outputs
    # fvm flutter pub run build_runner build